name: ex_map
version: 0.10.1
author: Vostrikov Vitaliy <rasart.pro@gmail.com>
description: A library for writing pretty simple object class with Map interface.
homepage: https://github.com/Rasarts/ExMap
environment:
  sdk: '>=1.14.0 <2.0.0'
dependencies:
  barback: '^0.15.2+8'
dev_dependencies:
  test: '^0.12.15+1'
  transformer_test: '^0.2.1'

transformers:
  - ex_map
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
